
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Aug 01 14:28:28 CDT 2017
//----------------------------------------------------

package pattern;

/** CUP generated class containing symbol constants. */
public class PatternSymbol {
  /* terminals */
  public static final int ENTITY = 16;
  public static final int LBRACE = 6;
  public static final int COLON = 14;
  public static final int CARET = 13;
  public static final int QUESTION = 10;
  public static final int EOF = 0;
  public static final int RPARAE = 3;
  public static final int VERLINE = 8;
  public static final int RBRACK = 5;
  public static final int COMMA = 9;
  public static final int LPARAE = 2;
  public static final int error = 1;
  public static final int RT = 12;
  public static final int LBRACK = 4;
  public static final int LT = 11;
  public static final int RBRACE = 7;
  public static final int KEYWORD = 15;
}

